<a href="https://colab.research.google.com/github/ZinoTAT/Machine-Learning/blob/master/pytorch/%E6%8D%9F%E5%A4%B1%E5%87%BD%E6%95%B0%E5%92%8C%E6%A2%AF%E5%BA%A6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn.functional as F
print(torch.__version__)

1.4.0


# MSE-均方根
$$
\begin{aligned}
loss=&\sum [y - f_\theta(x)]^2\\
\frac{\partial loss}{\partial \theta}=&2\sum [y-f_\theta(x)]\times \frac{\partial f_\theta(x)}{\partial\theta}
\end{aligned}
$$
torch.nn.functional.mse_loss(predict, label)


In [0]:
x = torch.ones(1)
w = torch.full([1], 2).requires_grad_() #带下滑线的方法表示in-place，会直接对该张量进行修改
mse = F.mse_loss(x * w, torch.ones(1))

# autograd


In [3]:
mse = F.mse_loss(x * w, torch.ones(1))
torch.autograd.grad(mse, [w])

(tensor([2.]),)

# backword
进行反向传播，并将导数值记录在参数的.grad中

In [4]:
mse = F.mse_loss(x * w, torch.ones(1))
mse.backward()
w.grad

tensor([2.])

# softmax


In [5]:
a = torch.rand(3).requires_grad_()
p = F.softmax(a, dim=0)
print(a)
print(p)

torch.autograd.grad(p[1], [a], retain_graph=True)
p[2].backward()
print(a.grad)

tensor([0.6324, 0.9944, 0.6505], requires_grad=True)
tensor([0.2895, 0.4158, 0.2948], grad_fn=<SoftmaxBackward>)
tensor([-0.0853, -0.1226,  0.2079])


# tips


1.   当grad维度特别高时，可以通过打印.norm()来判断grad大小



In [6]:
a.grad.norm()

tensor(0.2560)