<a href="https://colab.research.google.com/github/ZinoTAT/Machine-Learning-Practices/blob/master/pytorch/%E5%BC%A0%E9%87%8F%E7%9A%84%E5%88%9D%E9%98%B6%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

张量的基础操作，文中仅给出常用的api和简单样例，详细可前往[pytorch官方文档](https://pytorch.org/docs/stable/index.html)搜索

In [2]:
import torch 
import numpy as np
print(torch.__version__)

1.4.0


# 张量的创建
张量的创建一般可以由numpy或list导入，也可以直接使用pytorh的api创建

## 从numpy或list导入张量

In [24]:
a = np.array([1, 2])
b = [1, 2]
print(torch.from_numpy(a))
print(torch.tensor(b))
print(torch.Tensor(b))
print(torch.FloatTensor(b))

tensor([1, 2])
tensor([1, 2])
tensor([1., 2.])
tensor([1., 2.])


## 使用pytoch创建张量

In [36]:
print(torch.rand(2, 3)) # 创建张量并用0到1的均匀分布初始化
print(torch.randn(2, 3)) # 创建张量并用标准正态分布初始化
print(torch.Tensor(2, 3)) # 创建张量但不进行初始化
print(torch.empty(2, 3)) # 创建张量但不进行初始化
print(torch.ones(2, 3))
print(torch.zeros(2, 3))
print(torch.eye(3, 4))
print(torch.arange(0, 10))
print(torch.linspace(0, 10, steps=4))

tensor([[0.6708, 0.1230, 0.3656],
        [0.0969, 0.9176, 0.2705]])
tensor([[ 0.5485,  0.0693,  0.2670],
        [ 1.5007, -0.3591, -0.5126]])
tensor([[ 2.3118e-35,  0.0000e+00,  2.6699e-01],
        [ 1.5007e+00, -3.5906e-01, -5.1258e-01]])
tensor([[ 2.3118e-35,  0.0000e+00,  2.6699e-01],
        [ 1.5007e+00, -3.5906e-01, -5.1258e-01]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0.0000,  3.3333,  6.6667, 10.0000])


# 张量的索引和切片


## 类python中list的索引方式

In [45]:
a = torch.randn(4, 3, 28, 28)
print(a.shape)
print(a[2:, 1, ..., ::2].shape)

torch.Size([4, 3, 28, 28])
torch.Size([2, 28, 14])


## 使用mask进行索引

In [46]:
a = torch.randn(3, 4)
print(a)
mask = a.ge(0.5)
print(mask)
print(torch.masked_select(a, mask))


tensor([[-0.7873,  0.5286,  0.9342,  1.1598],
        [ 0.0788,  0.4924,  0.8003,  2.0119],
        [-0.5521, -1.5743, -0.3063,  1.0140]])
tensor([[False,  True,  True,  True],
        [False, False,  True,  True],
        [False, False, False,  True]])
tensor([0.5286, 0.9342, 1.1598, 0.8003, 2.0119, 1.0140])


## 会将结果拍平的索引方式

In [47]:
a = torch.tensor([[4, 3, 5], [6, 7, 8]])
print(torch.take(a, torch.tensor([0, 2, 5])))

tensor([4, 5, 8])


# 张量的维度变换

## 维度的增加和删减
unsqueeze(int index) index为要插入的维度的位置，0表示第一个位置， -1表示最后一个位置\
squeeze(int dim) 选择要删除的维度，当该维度长度大于1时不变,参数为空时删除所有长度为1的维度

In [4]:
a = torch.rand(3, 4)
us = a.unsqueeze(1).unsqueeze(-1)
print(us.shape)
print(a.unsqueeze(-2).shape)

torch.Size([3, 1, 4, 1])
torch.Size([3, 1, 4])


In [5]:
print("us.shape: ", us.shape)
print(us.squeeze(1).shape) #当前选择维度的长度为1，删除
print(us.squeeze(2).shape) #当前选择维度的长度不为1，保持不变
print(us.squeeze().shape) #删除所有长度为1的维度

us.shape:  torch.Size([3, 1, 4, 1])
torch.Size([3, 4, 1])
torch.Size([3, 1, 4, 1])
torch.Size([3, 4])


## 维度的扩展
expand(dim0, dim1, ...) 参数为各维度扩展后的长度，-1表示不变(推荐使用)\
repeat(index0, index1, ...) 参数为各维度要复制的次数

In [7]:
a = torch.rand(4, 32, 14, 14)
b = torch.rand(1, 32, 1, 1)
print(b.shape)
print(b.expand(4, -1, 14, 14).shape)
print(b.repeat(4, 1, 14, 14).shape)

torch.Size([1, 32, 1, 1])
torch.Size([4, 32, 14, 14])
torch.Size([4, 32, 14, 14])


## 转置（维度的交换操作）
transpose(dim1, dim2)dim1，dim2为要交换的两个维度
contiguous 将张量的存储重新变得有序，在transpose操作之后使用
permute(dim1, dim2, dim3, ...)参数为重新排列前维度系数

In [18]:
a = torch.rand(4, 32, 14, 14)
a1 = a.permute(0, 3, 1, 2).contiguous()
a2 = a.transpose(1, 3).transpose(2, 3).contiguous()
print(a1.shape, a2.shape)
print(torch.all(torch.eq(a1, a2)))

torch.Size([4, 14, 32, 14]) torch.Size([4, 14, 32, 14])
tensor(True)
